module.exports = {
  GROUP_MEMBER_UI_LIMIT: 100,
  MAX_DIRECT_UPLOAD_BYTES: 10 * 1024 * 1024,
  JWT_REAUTH_DAYS: 90,
  AI_MODERATOR_FALLBACK_STATUS: "REQUEST_SENT_TO_MODERATOR",
  MOSCOW_TZ: "Europe/Moscow",
  KHABAROVSK_TZ: "Asia/Vladivostok"
};
